spring.application.name=soa-gateway

server.port=8080


# =========================================================
# PRODUCT SERVICE ROUTE
# =========================================================

spring.cloud.gateway.server.webflux.routes[0].id=product-service

spring.cloud.gateway.server.webflux.routes[0].uri=https://dummyjson.com

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/products/**


# =========================================================
# CART SERVICE ROUTE
# =========================================================

spring.cloud.gateway.server.webflux.routes[1].id=cart-service

spring.cloud.gateway.server.webflux.routes[1].uri=https://dummyjson.com

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/carts/**


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always